version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn test
            - run: sudo apt-get update && sudo apt-get install -y python-dev
            - run: sudo curl -0 https://bootstrap.pypa.io/get-pip.py
            - run: sudo python get-pip.py
            - run: sudo pip install awscli --upgrade
            - run: aws --version
            - run: aws s3 ls
            - run: yarn deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - build-and-deploy