version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws: circlci/aws-cli@0.1.22
jobs:
  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn build
            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    executor:
      name: aws/default
    steps:
      - checkout
      - aws/with-cache:
          steps:
            - run: aws s3 sync build/ s3://ocx-web-app --delete
          
workflows:
    build-and-test:
      jobs:
        - install-and-test
        - build
        - deploy