version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws: circleci/aws-s3@1.0.15
jobs:
  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn build
            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    steps:
      - checkout
      - aws/sync:
          from: build/
          to: "s3://ocx-web-app"
          overwrite: true
          
workflows:
    test-build-deploy:
      jobs:
        - install-and-test
        - build
        - deploy